import re
from collections import Counter


# -------------------------------------------------------------------
# Patterns that are usually UI/navigation noise.
# These are deliberately conservative.
# -------------------------------------------------------------------

UI_LINE_PATTERNS = [
    r"^\s*skip to (?:main )?content\s*$",
    r"^\s*(open|close) (?:menu|navigation)\s*$",
    r"^\s*(previous|next)\s*$",
    r"^\s*(back|forward)\s*$",
    r"^\s*(sign in|log in|sign up|register)\s*$",
    r"^\s*(cookie settings|accept cookies)\s*$",
]


# Metadata fields commonly generated by documentation websites.
UI_METADATA_FIELDS = (
    "schema_version",
    "panelId",
    "clientId",
    "clientName",
    "componentId",
    "elementId",
    "tabId",
    "langId",
    "languageId",
    "data-testid",
    "data-component",
    "ariaLabel",
)


def clean_text(text: str) -> str:
    """
    General-purpose cleaner for ArchLens documents.

    Important:
        This function removes extraction noise but attempts to
        preserve technical information.

    Preserved intentionally:
        - Markdown headings
        - Markdown tables
        - URLs
        - code blocks
        - JSON/YAML examples
        - configuration
        - technical terminology
    """

    if not text:
        return ""

    # ---------------------------------------------------------------
    # 1. Normalize basic Unicode / line endings
    # ---------------------------------------------------------------

    text = normalize_unicode(text)

    # ---------------------------------------------------------------
    # 2. Remove HTML elements that contain no useful content
    # ---------------------------------------------------------------

    text = remove_html_noise(text)

    # ---------------------------------------------------------------
    # 3. Remove obvious documentation-site metadata
    # ---------------------------------------------------------------

    text = remove_documentation_metadata(text)

    # ---------------------------------------------------------------
    # 4. Remove tracking fragments
    # ---------------------------------------------------------------

    text = remove_tracking_noise(text)

    # ---------------------------------------------------------------
    # 5. Remove obvious UI-only lines
    # ---------------------------------------------------------------

    text = remove_ui_lines(text)

    # ---------------------------------------------------------------
    # 6. Remove PDF page-number noise
    # ---------------------------------------------------------------

    text = remove_page_number_noise(text)

    # ---------------------------------------------------------------
    # 7. Remove repeated headers / footers
    # ---------------------------------------------------------------

    text = remove_repeated_lines(text)

    # ---------------------------------------------------------------
    # 8. Repair common extraction problems
    # ---------------------------------------------------------------

    text = repair_line_breaks(text)

    # ---------------------------------------------------------------
    # 9. Normalize whitespace
    # ---------------------------------------------------------------

    text = normalize_whitespace(text)

    return text.strip()


# ===================================================================
# Unicode / basic normalization
# ===================================================================

def normalize_unicode(text: str) -> str:
    """Normalize characters commonly introduced by web/PDF extraction."""

    text = text.replace("\r\n", "\n")
    text = text.replace("\r", "\n")
    text = text.replace("\x00", "")

    # Non-breaking space.
    text = text.replace("\xa0", " ")

    # Zero-width characters.
    text = re.sub(
        r"[\u200b\u200c\u200d\ufeff]",
        "",
        text,
    )

    # Common typography substitutions.
    replacements = {
        "\u2018": "'",
        "\u2019": "'",
        "\u201c": '"',
        "\u201d": '"',
        "\u2013": "-",
        "\u2014": "--",
        "\u2212": "-",
        "\u2026": "...",
        "\u00ad": "",  # soft hyphen
    }

    for old, new in replacements.items():
        text = text.replace(old, new)

    return text


# ===================================================================
# HTML
# ===================================================================

def remove_html_noise(text: str) -> str:
    """
    Remove HTML tags and elements that generally contain
    non-document content.

    This is useful when raw HTML was saved rather than first
    converted to text by loader.py.
    """

    # Remove script/style/template blocks completely.
    text = re.sub(
        r"<(script|style|noscript|template|svg).*?>.*?</\1>",
        "",
        text,
        flags=re.IGNORECASE | re.DOTALL,
    )

    # Remove comments.
    text = re.sub(
        r"<!--.*?-->",
        "",
        text,
        flags=re.DOTALL,
    )

    # Convert common block elements into line breaks before
    # removing remaining tags.
    text = re.sub(
        r"</?(?:p|div|section|article|header|footer|main|li|tr|h[1-6])[^>]*>",
        "\n",
        text,
        flags=re.IGNORECASE,
    )

    # Remove remaining HTML tags.
    text = re.sub(
        r"<[^>]+>",
        "",
        text,
    )

    return text


# ===================================================================
# Documentation-site metadata
# ===================================================================

def remove_documentation_metadata(text: str) -> str:
    """
    Remove metadata generated by documentation websites.

    Example of unwanted content:

        ```json metadata
        {
            "schema_version": 2,
            "title": "Redis Pub/Sub",
            "tableOfContents": {...},
            "codeExamples": []
        }
        ```

    Also removes standalone UI metadata objects containing fields
    such as clientId/panelId.

    We deliberately avoid deleting arbitrary JSON because legitimate
    technical JSON examples are valuable to ArchLens.
    """

    # ---------------------------------------------------------------
    # Markdown fenced metadata blocks
    # ---------------------------------------------------------------

    metadata_fence = re.compile(
        r"```(?:json|javascript|js)?\s+metadata\b.*?```",
        flags=re.IGNORECASE | re.DOTALL,
    )

    text = metadata_fence.sub("", text)

    # ---------------------------------------------------------------
    # Fenced blocks explicitly labelled metadata
    # ---------------------------------------------------------------

    text = re.sub(
        r"```\s*metadata\b.*?```",
        "",
        text,
        flags=re.IGNORECASE | re.DOTALL,
    )

    # ---------------------------------------------------------------
    # Remove standalone JSON objects that clearly contain
    # documentation UI metadata.
    #
    # Do NOT remove ordinary JSON examples.
    # ---------------------------------------------------------------

    text = remove_ui_json_objects(text)

    # ---------------------------------------------------------------
    # Remove lines containing highly distinctive UI metadata fields.
    # ---------------------------------------------------------------

    lines = text.splitlines()
    cleaned = []

    for line in lines:

        if contains_ui_metadata_field(line):
            continue

        cleaned.append(line)

    return "\n".join(cleaned)


def contains_ui_metadata_field(line: str) -> bool:
    """Check whether a line contains a documentation UI field."""

    for field in UI_METADATA_FIELDS:

        pattern = rf'["\']?{re.escape(field)}["\']?\s*:'

        if re.search(
            pattern,
            line,
            flags=re.IGNORECASE,
        ):
            return True

    return False


def remove_ui_json_objects(text: str) -> str:
    """
    Remove balanced JSON objects that clearly represent UI metadata.

    This uses a small brace scanner rather than a greedy regex so
    nested objects don't accidentally consume technical content.
    """

    result = []
    i = 0

    while i < len(text):

        if text[i] != "{":
            result.append(text[i])
            i += 1
            continue

        # Try to find the matching closing brace.
        end = find_matching_brace(text, i)

        if end is None:
            result.append(text[i])
            i += 1
            continue

        candidate = text[i:end + 1]

        if is_ui_metadata_object(candidate):
            # Preserve a newline so surrounding paragraphs don't merge.
            result.append("\n")
        else:
            result.append(candidate)

        i = end + 1

    return "".join(result)


def find_matching_brace(
    text: str,
    start: int,
):
    """
    Find the closing brace corresponding to an opening brace.

    Handles quoted strings reasonably well so braces inside strings
    don't break the scan.
    """

    depth = 0
    in_string = False
    escape = False

    for i in range(start, len(text)):

        char = text[i]

        if escape:
            escape = False
            continue

        if char == "\\" and in_string:
            escape = True
            continue

        if char == '"':
            in_string = not in_string
            continue

        if in_string:
            continue

        if char == "{":
            depth += 1

        elif char == "}":
            depth -= 1

            if depth == 0:
                return i

    return None


def is_ui_metadata_object(candidate: str) -> bool:
    """Determine whether a JSON-like object is documentation UI metadata."""

    field_count = 0

    for field in UI_METADATA_FIELDS:

        if re.search(
            rf'["\']?{re.escape(field)}["\']?\s*:',
            candidate,
            flags=re.IGNORECASE,
        ):
            field_count += 1

    # A single distinctive UI field can be enough for small objects.
    return field_count >= 1


# ===================================================================
# Tracking
# ===================================================================

def remove_tracking_noise(text: str) -> str:
    """
    Remove common URL tracking parameters.

    Normal URLs are preserved because ArchLens needs them for citations.
    """

    patterns = [
        r"utm_[a-zA-Z0-9_]+\s*=\s*[^&\s]+",
        r"fbclid=[^&\s]+",
        r"gclid=[^&\s]+",
        r"mc_cid=[^&\s]+",
        r"mc_eid=[^&\s]+",
    ]

    for pattern in patterns:
        text = re.sub(
            pattern,
            "",
            text,
            flags=re.IGNORECASE,
        )

    return text


# ===================================================================
# UI lines
# ===================================================================

def remove_ui_lines(text: str) -> str:
    """Remove standalone navigation/UI lines."""

    lines = text.splitlines()
    result = []

    for line in lines:

        stripped = line.strip()

        if not stripped:
            result.append("")
            continue

        should_remove = any(
            re.match(
                pattern,
                stripped,
                flags=re.IGNORECASE,
            )
            for pattern in UI_LINE_PATTERNS
        )

        if not should_remove:
            result.append(line.rstrip())

    return "\n".join(result)


# ===================================================================
# PDF page numbers / repeated headers
# ===================================================================

def remove_page_number_noise(text: str) -> str:
    """Remove standalone PDF page numbers."""

    lines = text.splitlines()
    result = []

    for line in lines:

        stripped = line.strip()

        # "37"
        if re.fullmatch(r"\d{1,4}", stripped):
            continue

        # "Page 37"
        if re.fullmatch(
            r"page\s+\d+",
            stripped,
            flags=re.IGNORECASE,
        ):
            continue

        # "Page 37 of 120"
        if re.fullmatch(
            r"page\s+\d+\s+of\s+\d+",
            stripped,
            flags=re.IGNORECASE,
        ):
            continue

        result.append(line)

    return "\n".join(result)


def remove_repeated_lines(
    text: str,
    min_occurrences: int = 3,
) -> str:
    """
    Remove repeated PDF headers/footers.

    Only relatively long lines are considered so that repeated
    technical terms are not accidentally removed.
    """

    lines = text.splitlines()

    normalized = [
        line.strip()
        for line in lines
        if line.strip()
    ]

    counts = Counter(normalized)

    repeated = {
        line
        for line, count in counts.items()
        if count >= min_occurrences
        and len(line) >= 15
    }

    result = []

    for line in lines:

        if line.strip() in repeated:
            continue

        result.append(line)

    return "\n".join(result)


# ===================================================================
# Line-break / PDF extraction repair
# ===================================================================

def repair_line_breaks(text: str) -> str:
    """
    Repair common PDF extraction problems.

    Handles:
        - words split at line boundaries
        - hyphenated words split across lines
        - sentences incorrectly joined across lines

    Does NOT modify code blocks or Markdown tables.
    """

    lines = text.splitlines()

    result = []

    in_code_block = False

    for i, line in enumerate(lines):

        # -----------------------------------------------------------
        # Track fenced code blocks.
        # -----------------------------------------------------------

        if line.strip().startswith("```"):
            in_code_block = not in_code_block
            result.append(line)
            continue

        # Never modify code blocks.
        if in_code_block:
            result.append(line)
            continue

        # Never modify Markdown table rows.
        if "|" in line and line.strip().startswith("|"):
            result.append(line)
            continue

        # -----------------------------------------------------------
        # Hyphenated word split:
        #
        # "distribu-\nted" -> "distributed"
        # -----------------------------------------------------------

        if (
            result
            and line.strip()
            and result[-1].endswith("-")
            and not result[-1].strip().startswith("-")
        ):
            previous = result.pop()

            result.append(
                previous[:-1] + line.strip()
            )

            continue

        result.append(line)

    text = "\n".join(result)

    # ---------------------------------------------------------------
    # Join words that were separated by a newline without punctuation.
    #
    # Example:
    #
    # "if\nany"
    #
    # -> "if any"
    #
    # This is deliberately conservative.
    # ---------------------------------------------------------------

    text = re.sub(
        r"(?<=[a-zA-Z,;:)])\n(?=[a-z])",
        " ",
        text,
    )

    return text


# ===================================================================
# Whitespace
# ===================================================================

def normalize_whitespace(text: str) -> str:
    """
    Normalize whitespace while preserving meaningful Markdown
    structure and code formatting reasonably well.
    """

    lines = text.splitlines()

    cleaned = []

    for line in lines:

        # Remove trailing whitespace.
        line = line.rstrip()

        # Avoid excessive spaces in ordinary text.
        if not line.strip().startswith("```"):
            line = re.sub(
                r"[ \t]{2,}",
                " ",
                line,
            )

        cleaned.append(line)

    text = "\n".join(cleaned)

    # Collapse excessive blank lines.
    text = re.sub(
        r"\n{3,}",
        "\n\n",
        text,
    )

    return text.strip()


# ===================================================================
# Public pipeline
# ===================================================================

def prepare_text(text: str) -> str:
    """
    Main entry point for document cleaning.

    Use this function before chunking.
    """

    return clean_text(text)